<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<OutputType>Library</OutputType>
		<RootNamespace>Cadastre_Calculator</RootNamespace>
		<AssemblyName>CadastreTools</AssemblyName>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoCAD.NET" Version="25.1.0" PrivateAssets="All" />
		<PackageReference Include="AutoCAD.NET.Core" Version="25.1.0" PrivateAssets="All" />
		<PackageReference Include="AutoCAD.NET.Model" Version="25.1.0" PrivateAssets="All" />
		<PackageReference Include="System.Text.Json" Version="9.0.2" />
		<PackageReference Include="NUnit" Version="4.1.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
		<PackageReference Include="Moq" Version="4.20.70" />
	</ItemGroup>



</Project>